### ISSUE TITLE
Postgres installation not detected on Ubuntu 18.04

### ISSUE THREAD

**Issue by hubyhuby** [gobuffalo/clara#1]
I can create a full working buffalo app with postgres on a frshely installed system with 0.14.3, 
but clara keeps telling me it is not on my system 

-> PostgreSQL: Checking installation
✘ The `postgres` executable could not be found on your system.
For help setting up your Postgres environment please follow the instructions for you platform at:

https://www.postgresql.org/download/

Thanks a LOT for this wonderfull clara tool !

**Comment by markbates** [comment]
That means the Postgres executable isn’t in your PATH. Add it.

**Comment by hubyhuby** [comment]
Thanks for the info.
I am running a standard package installation of Postgres on Ubuntu 18.04 LTS. I suppose anyone running this distro will have this false negative ... Maybe an improvement could be to state, "the Postgres executable isn’t in your PATH. ( Also your Postgres might be installed  properly) "

**Comment by hubyhuby** [comment]
I have double checked and psql seem to be in my path. I am 0 problem with psql.
This is the result of a second ubuntu 18.04 LTs install that gives the same thing.
Also it seems that it is a "link" : Lien vers script Perl (application/x-perl)

$PATH
bash: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/s ...
![image](https://user-images.githubusercontent.com/26340942/58006974-8ba00700-7ae9-11e9-929b-7e682db00cbd.png)
