### ISSUE TITLE
options.go errors flagged when trying to go get clara

### ISSUE THREAD

**Issue by gViro** [gobuffalo/clara#5]
`go get -u github.com/gobuffalo/clara` fails with the following errors: 

`# github.com/gobuffalo/clara/genny/rx

go/src/github.com/gobuffalo/clara/genny/rx/**options.go:22:13**: _opts.App.IsZero undefined (type meta.App has no field or method IsZero)_

go/src/github.com/gobuffalo/clara/genny/rx/**options.go:23:12**: _assignment mismatch: 1 variable but meta.New returns 2 values_

go/src/github.com/gobuffalo/clara/genny/rx/**options.go:23:23**: _cannot use "." (type string) as type here.Info in argument to meta.New_`

**Comment by breml** [comment]
Try to execute `go get` outside of the `GOPATH` or enable Go modules with `GO111MODULE=on`. For me, this resolved the issue.

**Comment by tcarreira** [comment]
I had this same problem and using `GO111MODULE=on go get -v github.com/gobuffalo/clara`  just did solve it. 
Would you consider adding this on the main README file?
