### ISSUE TITLE
Detection of Go version is (potentially) wrong

### ISSUE THREAD

**Issue by breml** [gobuffalo/clara#6]
The line https://github.com/gobuffalo/clara/blob/master/genny/rx/go_checks.go#L24 does report the Go version, clara is built with and not the Go version, that is currently used by the system.

I use a Go version manager and depending on which version I select, the environment variables (e.g. `GOROOT`) are defined accordingly. This is ignored by clara for the version check (even though, the location of the `go` command is detected correctly.

**Comment by sio4** [comment]
Thank you for reporting this hidden issue. I really didn't notice it. I fixed it yesterday and now released it as a new version. The buffalo CLI applied this fix will be released soon too!

Thank you again!
